using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TheyDontStopComing {
	public class MapStore {
		public string[,] maps = {
			{
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"       #######       ",
				"       #     #       ",
				"       # S E #       ",
				"       #     #       ",
				"       #######       ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     "
			},
			{
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"       #######       ",
				"       #     #       ",
				"       #AS E #       ",
				"       #     #       ",
				"       #######       ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     "
			},
			{
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"       #######       ",
				"       #     #       ",
				"       # SAE #       ",
				"       #     #       ",
				"       #######       ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     "
			},
			{
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"       #######       ",
				"       #A   A#       ",
				"       # SAE #       ",
				"       #     #       ",
				"       #######       ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     "
			},
			{
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"       #######       ",
				"       #  A  #       ",
				"       ##### #       ",
				"       #S   E#       ",
				"       ##### #       ",
				"       # A   #       ",
				"       #######       ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     "
			},
			{
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"     ###########     ",
				"     #         #     ",
				"     # ####### #     ",
				"     # #   ### #     ",
				"     #S     AAE#     ",
				"     # #   ### #     ",
				"     # ####### #     ",
				"     #         #     ",
				"     ###########     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     "
			},
			{
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"         ###         ",
				"      ####A####      ",
				"      #S  C E #      ",
				"      #########      ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     "
			},
			{
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"        ###          ",
				"        # ###        ",
				"      ###CA ###      ",
				"      #S  C E #      ",
				"      ###  ####      ",
				"        ####         ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     "
			},
			{
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"       ########      ",
				"       #A     #      ",
				"      ####### #      ",
				"      #A    # #      ",
				"      ###   CN#      ",
				"      #S    CN#      ",
				"      ###  #  #      ",
				"      #A   #NE#      ",
				"      #########      ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     "
			},
			{
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"      #########      ",
				"      # A A A #      ",
				"      #GGGGGGG#      ",
				"      #S#####E#      ",
				"      #       #      ",
				"      # A A A #      ",
				"      #########      ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     ",
				"                     "
			},
			{
				"#####################",
				"#                   #",
				"#                   #",
				"#                   #",
				"#    ####           #",
				"#   #  E#           #",
				"#  #N A #           #",
				"# # CCN#            #",
				"## CC #             #",
				"# CC #              #",
				"#SC #               #",
				"####                #",
				"#                   #",
				"#                   #",
				"#                   #",
				"#                   #",
				"#                   #",
				"#                   #",
				"#                   #",
				"#                   #",
				"#####################"
			}
		};

		public string[] levelText = {
			"LIFE AS A GREEN SQUARE GETS RATHER BORING",
			"BUT THERE ARE OTHERS IN THIS WORLD",
			"THEY MIGHT GET IN THE WAY",
			"ALWAYS FAR TOO CLINGY",
			"THEY MIGHT NOT BE FAST ENOUGH",
			"OR THEY MIGHT SEARCH THE WRONG WAY",
			"OTHER INTERACTIONS AREN'T UNCOMMON",
			"BUT THESE CAN'T ALWAYS BE CONTROLLED",
			"AND THEY CAN'T MOVE EVERYWHERE, EITHER",
			"SOME AREAS ARE SAFER THAN OTHERS",
			"BUT LIFE IS JUST ONE BIG PUZZLE"
		};
	}
}
